# Generated by Django 5.2.6 on 2025-10-02 06:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClipRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("youtube_url", models.URLField()),
                ("start_time", models.IntegerField()),
                ("end_time", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "original_title",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("video_duration", models.IntegerField(blank=True, null=True)),
                (
                    "channel_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("channel_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "processing_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("download_and_clip", "Download Full Video and Clip"),
                            ("download_sections", "Download Specific Sections"),
                            ("ffmpeg_stream", "FFmpeg Stream Processing"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("processing_log", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "clip_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClipAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("video_id", models.CharField(max_length=50)),
                ("video_duration", models.IntegerField()),
                ("clip_duration", models.IntegerField()),
                ("clip_percentage", models.FloatField()),
                ("processing_method", models.CharField(max_length=30)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("download_size", models.BigIntegerField(blank=True, null=True)),
                ("final_file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "channel_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("channel_id", models.CharField(blank=True, max_length=100, null=True)),
                ("user_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("referrer", models.URLField(blank=True, null=True)),
                ("server_load", models.FloatField(blank=True, null=True)),
                ("memory_usage", models.FloatField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("error_type", models.CharField(blank=True, max_length=100, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "clip_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="home.cliprequest",
                    ),
                ),
            ],
            options={
                "db_table": "clip_analytics",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["video_id"], name="clip_analyt_video_i_a3dc20_idx"
                    ),
                    models.Index(
                        fields=["channel_id"], name="clip_analyt_channel_ad1091_idx"
                    ),
                    models.Index(
                        fields=["processing_method"],
                        name="clip_analyt_process_d0ca2c_idx",
                    ),
                    models.Index(
                        fields=["success"], name="clip_analyt_success_0b03aa_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="clip_analyt_created_9593ff_idx"
                    ),
                ],
            },
        ),
    ]
