# Generated by Django 5.2.6 on 2025-12-03 16:53

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import home.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(blank=True, max_length=150)),
                ("is_verified", models.BooleanField(default=False)),
                ("phone", models.BigIntegerField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ClipRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("youtube_url", models.URLField()),
                ("start_time", models.IntegerField()),
                ("end_time", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clip_720p",
                    models.FileField(
                        blank=True, null=True, upload_to=home.models.clip_file_path
                    ),
                ),
                (
                    "clip_480p",
                    models.FileField(
                        blank=True, null=True, upload_to=home.models.clip_file_path
                    ),
                ),
                (
                    "original_title",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "clip_720p_size",
                    models.BigIntegerField(
                        blank=True, help_text="clip size in mb", null=True
                    ),
                ),
                (
                    "clip_480p_size",
                    models.BigIntegerField(
                        blank=True, help_text="clip size in mb", null=True
                    ),
                ),
                ("clip_duration", models.IntegerField(blank=True, null=True)),
                (
                    "channel_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("channel_id", models.CharField(blank=True, max_length=100, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("total_time_taken", models.IntegerField(blank=True, null=True)),
                ("processing_log", models.JSONField(blank=True, default=dict)),
                ("rq_job_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "clip_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClipAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("video_id", models.CharField(max_length=50)),
                ("video_duration", models.IntegerField()),
                ("clip_duration", models.IntegerField()),
                ("clip_percentage", models.FloatField()),
                ("processing_method", models.CharField(max_length=30)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("download_size", models.BigIntegerField(blank=True, null=True)),
                ("final_file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "channel_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("channel_id", models.CharField(blank=True, max_length=100, null=True)),
                ("user_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("referrer", models.URLField(blank=True, null=True)),
                ("server_load", models.FloatField(blank=True, null=True)),
                ("memory_usage", models.FloatField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("error_type", models.CharField(blank=True, max_length=100, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "clip_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="home.cliprequest",
                    ),
                ),
            ],
            options={
                "db_table": "clip_analytics",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["video_id"], name="clip_analyt_video_i_a3dc20_idx"
                    ),
                    models.Index(
                        fields=["channel_id"], name="clip_analyt_channel_ad1091_idx"
                    ),
                    models.Index(
                        fields=["processing_method"],
                        name="clip_analyt_process_d0ca2c_idx",
                    ),
                    models.Index(
                        fields=["success"], name="clip_analyt_success_0b03aa_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="clip_analyt_created_9593ff_idx"
                    ),
                ],
            },
        ),
    ]
