# Generated by Django 5.2.6 on 2025-12-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliprequest",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="cliprequest",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
